
# @name login
POST https://vntravel-api.herokuapp.com/app/api/v1/auths/login/users?userRole=false
Content-Type: application/json

{
    "email": "thaole301000@gmail.com",
    "password" : "12345"
}

###
@authToken = {{login.response.body.token}}
###

### Create new place
POST  http://localhost:5000/app/api/v1/places
Content-Type: application/json
Authorization: token {{authToken}}

{
    "name": "Phố cổ Hội An",
    "description": "Phố cổ Hội An là một thành phố nổi tiếng của tỉnh Quảng Nam, một phố cổ giữ được gần như nguyên vẹn với hơn 1000 di tích kiến trúc từ phố xá, nhà cửa, hội quán, đình, chùa, miếu, nhà thờ tộc, giếng cổ… đến các món ăn truyền thống, tâm hồn của người dân nơi đây. Một lần du lịch Hội An sẽ làm say đắm lòng du khách bởi những nét đẹp trường tồn cùng thời gian, vô cùng mộc mạc, bình dị.",
    "address":"TL 7",
    "longtitude": 15.8801,
    "lattitude": 108.3380,
    "tags":[],
    "rate": 5,
    "weight": 10,
    "province" :"6191295841e6f727b4247a33",
    "category":"612f41c7e410f520706e6428",
    "startPrice":"20000",
    "endPrice":"80000",
    "closeTime": "18:5",
    "openTime": "7:5",
    "status":"public", 
    "popular":true

}
### Add image to place
POST http://localhost:5000/app/api/v1/places/613add51a784f131b084e56e/images
Content-Type: application/json

{
    images:"https://cdnmedia.thethaovanhoa.vn/Upload/tyTrfgkgEUQwPYuvZ4Kn1g/files/2019/07/1607/hoi-an.jpghttps://cdnmedia.thethaovanhoa.vn/Upload/tyTrfgkgEUQwPYuvZ4Kn1g/files/2019/07/1607/hoi-an.jpg"
}
### Get place

GET http://localhost:5000/app/api/v1/places/613b1da30ea0491390fa5bb0?populate=true
Content-Type: application/json


### Get places

GET https://vntravel-api.herokuapp.com/app/api/v1/places/private?populate=true
Content-Type: application/json

### Update images inplace
PUT http://localhost:5000/app/api/v1/places/613b1da30ea0491390fa5bb0/images
Content-Type: application/json
Authorization: token {{authToken}}

{
    "id":"613b1da30ea0491390fa5bb0",
    "images":["https://cdn1.nhatrangtoday.vn/images/photos/kinh-nghiem-dat-ve-xe-nha-trang-da-lat-1.jpg","https://www.vietnambooking.com/wp-content/uploads/2020/12/kinh-nghiem-di-da-lat-thang-12-1.jpg"
    ]
}
###FIND PLACES CONTAIN TAG ID
PUT http://localhost:5000/app/api/v1/places/find/tags
Content-Type: application/json
Authorization: token {{authToken}}

{
    "tags":["614c287428cff4001670150c", "614c018a27c6e100160c06fc"]
}

#### GET PLACE OF ONE CATEGORY
GET http://localhost:5000/app/api/v1/places/category/612f41c7e410f520706e6428
Content-Type: application/json
Authorization: token {{authToken}}

#### GET PLACE OF ONE province
GET http://localhost:5000/app/api/v1/places/province/612f41c7e410f520706e6428
Content-Type: application/json
Authorization: token {{authToken}}
###
POST http://localhost:5000/app/api/v1/places/suggestion
Content-Type: application/json

{
    "text": "sư p"
}

####

GET http://localhost:5000/app/api/v1/places/popular/topRating

####

GET http://localhost:5000/app/api/v1/places/nearBy/6191295841e6f727b4247a33/613b1da30ea0491390fa5bb0