### Get plan of user

GET http://localhost:5000/app/api/v1/plans
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQXV0aCI6eyJpZCI6IjYxOGRjY2YwM2U2NTFhMGUwMGZiMTVjYSIsImVtYWlsIjoibmh1bmdsZUBnbWFpbC5jb20iLCJpc1VzZXIiOnRydWUsImltYWdlIjoiaHR0cHM6Ly9oaW5obmVuMTIzLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAyMS8wNi9hdnQtY3V0ZS05LmpwZyIsIm5hbWUiOiJMZSBUaGkgTmdvYyBOaHVuZyJ9LCJpYXQiOjE2Mzg0MzE2MjQsImV4cCI6MTYzODQ2MDQyNH0.5f5YibyCebHaFTTozr_WKyhBwBplWr-md0XMHBUrDv8
### Create new plan 

POST http://localhost:5000/app/api/v1/plans
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQXV0aCI6eyJpZCI6IjYxOGRjY2YwM2U2NTFhMGUwMGZiMTVjYSIsImVtYWlsIjoibmh1bmdsZUBnbWFpbC5jb20iLCJpc1VzZXIiOnRydWUsImltYWdlIjoiaHR0cHM6Ly9oaW5obmVuMTIzLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAyMS8wNi9hdnQtY3V0ZS05LmpwZyIsIm5hbWUiOiJMZSBUaGkgTmdvYyBOaHVuZyJ9LCJpYXQiOjE2Mzg0MzE2MjQsImV4cCI6MTYzODQ2MDQyNH0.5f5YibyCebHaFTTozr_WKyhBwBplWr-md0XMHBUrDv8

{
    "name":"Nghỉ mát Vịnh Hạ Long",
    "start": "2021-12-01T06:00:00",
    "end": "2021-12-06T18:00:00",
    "note": "Mua quà lưu niệm",
    "photoUrl": "https://wallpaperaccess.com/full/200944.jpg"
}

### Update isHidden
DELETE   http://localhost:5000/app/api/v1/plans/61b459a302f7af19e8ac537e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQXV0aCI6eyJpZCI6IjYxOGRjY2YwM2U2NTFhMGUwMGZiMTVjYSIsImVtYWlsIjoibmh1bmdsZUBnbWFpbC5jb20iLCJpc1VzZXIiOnRydWUsImltYWdlIjoiaHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vdm50cmF2ZWwyODUzNjYvaW1hZ2UvdXBsb2FkL3YxNjM4ODczNTY1L2h5MTVuZnJ3ZnhwZXZsemQya2tsLmpwZyIsIm5hbWUiOiJUaGFvIExlZWUifSwiaWF0IjoxNjM5MjEzODc0LCJleHAiOjE2MzkyNDI2NzR9.jsvPnsbQdOETLhDSpmZuk34UYXYmJ84PKvckvQSuNGI

### Update a plan 

PUT http://localhost:5000/app/api/v1/plans/6120b3a62d25ff10bc0bb845
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQXV0aCI6eyJmYXZvcml0ZSI6W10sImlzVXNlciI6dHJ1ZSwiZW1haWwiOiJob2FuZ25ndXllbjEyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFZJRlBIZWt4cW4ucWdkUFVXVGlURmVtOE5DR0lTYkloWlRlY29aRGNlVFhlbU5hbVRXOFJpIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0yMFQyMDozOTo0MS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0yMFQyMDozOTo0MS4wMDBaIiwiaWQiOiI2MTFmYjA5ZGI2MmU2NTNjNGM4NThhYjgifSwiaWF0IjoxNjI5NTMwNjkwLCJleHAiOjE2Mjk1NTk0OTB9.GHYwFbCLGSktjHSjfuTXPfcbkcHs4pyH4HXcIxnQQwE

{
    "start": "2021-08-20T03:00:00"
}