# @name login
POST https://vntravel-api.herokuapp.com/app/api/v1/auths/login/users?userRole=false
Content-Type: application/json

{
    "email": "thaole301000@gmail.com",
    "password" : "12345"
}

###
@authToken = {{login.response.body.token}}
###

### Province
###
GET http://localhost:5000/app/api/v1/provinces
Content-Type: application/json


### 
POST http://localhost:5000/app/api/v1/provinces/
Content-Type: application/json
Authorization: token {{authToken}}

{
    "name": "Quan 1",
    "color":"#f5f5f5"
}

### 
PUT https://vntravel-api.herokuapp.com/app/api/v1/provinces/614bdd73885f3700161f71c1
Content-Type: application/json
Authorization: token {{authToken}}

{
    "name": "Hello 1",
    "isHidden": false,
    "color":"#0000"
}

### 
DELETE  http://localhost:5000/app/api/v1/provinces/611e2ace95dcd508f4706781
Content-Type: application/json
Authorization: token {{authToken}}
