
### Create new review

POST http://localhost:5000/app/api/v1/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQXV0aCI6eyJmYXZvcml0ZSI6W10sImlzVXNlciI6dHJ1ZSwiZW1haWwiOiJob2FuZ25ndXllbjEyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGhBLll4U0xkWUJCMGZidmtBRkh1aHUwL01zTHRVek9ycmJ6M0F0WWNtLmZMM2MwNXZNL2MuIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xOFQxNDo0MDoyMS4wMDJaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xOFQxNDo0MDoyMS4wMDJaIiwiaWQiOiI2MTFkMWJkNDdlNGM1NTI4MzQzZWY5MGEifSwiaWF0IjoxNjI5NDQ4MzE2LCJleHAiOjE2Mjk0NTE5MTZ9.Owt3aL0YhWmRlCztF6R0qr7b3ediz1m7R8BXWOzICkg

{
    "title": "Memorable journey",
    "content": "The lanscape is so beautiful, people are so friendly and hospitable",
    "rate": 5,
    "place": "611930190aab361378748f0b",
    "visitedTime": "2021-08-20T09:50:00"
}

### Get reviews by place Id
GET http://localhost:5000/app/api/v1/reviews/611930190aab361378748f0b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQXV0aCI6eyJmYXZvcml0ZSI6WyI2MTFiNzdjN2EzYTM4NTQwOThmM2Y3ZjIiLCI2MTE5MzAxOTBhYWIzNjEzNzg3NDhmMGIiXSwiaXNVc2VyIjpmYWxzZSwiZW1haWwiOiJob2FuZ25ndXllbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRlbDJJSFRkcElGd0QxZHlHLmZGT291bC9ZeWVKYXdXQXRTUFhlUVAvRUJ5Vm81dXJWM3plZSIsImNyZWF0ZWRBdCI6IjIwMjEtMDgtMTdUMDY6MjE6MTAuNzkyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDgtMTdUMDY6MjE6MTAuNzkyWiIsImlkIjoiNjExYjU1NTZmZjEwMTMyMjYwZDllMjc5In0sImlhdCI6MTYyOTQ0OTU3OSwiZXhwIjoxNjI5NDUzMTc5fQ.EkuIwcrsMxB9SdnsJgCinNKEj8IMLiNbblrHWwFmu8g

### Put update like status
PUT http://localhost:5000/app/api/v1/reviews/liked/611f6d453dcc50211c3195fe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQXV0aCI6eyJmYXZvcml0ZSI6WyI2MTFiNzdjN2EzYTM4NTQwOThmM2Y3ZjIiLCI2MTE5MzAxOTBhYWIzNjEzNzg3NDhmMGIiXSwiaXNVc2VyIjpmYWxzZSwiZW1haWwiOiJob2FuZ25ndXllbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRlbDJJSFRkcElGd0QxZHlHLmZGT291bC9ZeWVKYXdXQXRTUFhlUVAvRUJ5Vm81dXJWM3plZSIsImNyZWF0ZWRBdCI6IjIwMjEtMDgtMTdUMDY6MjE6MTAuNzkyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDgtMTdUMDY6MjE6MTAuNzkyWiIsImlkIjoiNjExYjU1NTZmZjEwMTMyMjYwZDllMjc5In0sImlhdCI6MTYyOTQ0OTU3OSwiZXhwIjoxNjI5NDUzMTc5fQ.EkuIwcrsMxB9SdnsJgCinNKEj8IMLiNbblrHWwFmu8g

### Put update isHidden status (Delete)
PUT http://localhost:5000/app/api/v1/reviews/delete/611f6d453dcc50211c3195fe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQXV0aCI6eyJmYXZvcml0ZSI6W10sImlzVXNlciI6dHJ1ZSwiZW1haWwiOiJob2FuZ25ndXllbjEyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGhBLll4U0xkWUJCMGZidmtBRkh1aHUwL01zTHRVek9ycmJ6M0F0WWNtLmZMM2MwNXZNL2MuIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xOFQxNDo0MDoyMS4wMDJaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xOFQxNDo0MDoyMS4wMDJaIiwiaWQiOiI2MTFkMWJkNDdlNGM1NTI4MzQzZWY5MGEifSwiaWF0IjoxNjI5NDQ4MzE2LCJleHAiOjE2Mjk0NTE5MTZ9.Owt3aL0YhWmRlCztF6R0qr7b3ediz1m7R8BXWOzICkg

