
# @name login
POST https://vntravel-api.herokuapp.com/app/api/v1/auths/login/users?userRole=false
Content-Type: application/json

{
    "email": "thaole301000@gmail.com",
    "password" : "12345"
}

###
@authToken = {{login.response.body.token}}
###
### Create new review

POST http://localhost:5000/app/api/v1/reviews
Content-Type: application/json
Authorization: token {{authToken}}

{
    "title": "GOOD",
    "content": "Today, it is so beautiful rather than before",
    "rate": 5,
    "place": "6149988c07ed963790367bd9",
    "visitedTime": "2021-09-23T10:50:00"
}

### Get reviews by place Id
GET http://localhost:5000/app/api/v1/reviews/614c017e27c6e100160c06f9
Content-Type: application/json
Authorization: token {{authToken}}

### Put update like status
PUT http://localhost:5000/app/api/v1/reviews/liked/611f6d453dcc50211c3195fe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQXV0aCI6eyJmYXZvcml0ZSI6WyI2MTFiNzdjN2EzYTM4NTQwOThmM2Y3ZjIiLCI2MTE5MzAxOTBhYWIzNjEzNzg3NDhmMGIiXSwiaXNVc2VyIjpmYWxzZSwiZW1haWwiOiJob2FuZ25ndXllbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRlbDJJSFRkcElGd0QxZHlHLmZGT291bC9ZeWVKYXdXQXRTUFhlUVAvRUJ5Vm81dXJWM3plZSIsImNyZWF0ZWRBdCI6IjIwMjEtMDgtMTdUMDY6MjE6MTAuNzkyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDgtMTdUMDY6MjE6MTAuNzkyWiIsImlkIjoiNjExYjU1NTZmZjEwMTMyMjYwZDllMjc5In0sImlhdCI6MTYyOTQ0OTU3OSwiZXhwIjoxNjI5NDUzMTc5fQ.EkuIwcrsMxB9SdnsJgCinNKEj8IMLiNbblrHWwFmu8g

### Put update isHidden status (Delete)
PUT http://localhost:5000/app/api/v1/reviews/delete/6155764141338b4a486073f2
Content-Type: application/json
Authorization: token {{authToken}}

{
    "isHidden": true
}
