###Register
POST http://localhost:5000/app/api/v1/auths/register
Content-Type: application/json

{
     "email": "nhungle@gmail.com",
    "password" : "12345",
    "fullName": "Le Thi Ngoc Nhung"
}

### Login by email password
# @name login
POST http://localhost:5000/app/api/v1/auths/login/users?userRole=true       
Content-Type: application/json

{
   "email": "nhungle@gmail.com",
   "password" : "12345"
}

###
@authToken = {{login.response.body.token}}
### Add favorite places
PUT http://localhost:5000/app/api/v1/users/favorite/611930190aab361378748f0b
Content-Type: application/json
Authorization: token {{authToken}}

###Get user 
GET http://localhost:5000/app/api/v1/users
Content-Type: application/json
Authorization: token {{authToken}}
###
PUT http://localhost:5000/app/api/v1/users/6131fdf6198dac30ecbfa6cd/status  
Content-Type: application/json
Authorization: token {{authToken}}

{
    "id":"6131fdf6198dac30ecbfa6cd",
    "isHidden": true
}

###
GET http://localhost:5000/app/api/v1/auths/verify
Content-Type: application/json
Authorization:  token {{authToken}}

### Update recent search
PUT http://localhost:5000/app/api/v1/users/recentSearch/613b1da30ea0491390fa5bb0
Content-Type: application/json
Authorization: token {{authToken}}
### Get recent search
GET http://localhost:5000/app/api/v1/users/recentSearch
Content-Type: application/json
Authorization: token {{authToken}}

### Add favorites
PUT http://localhost:5000/app/api/v1/users/favorite/613f4f867963b61e40efe78a
Content-Type: application/json
Authorization: token {{authToken}}

### Delete favorites
DELETE http://localhost:5000/app/api/v1/users/favorite/613f4f867963b61e40efe78a
Content-Type: application/json
Authorization: token {{authToken}}

###Update Profile
POST   http://localhost:5000/app/api/v1/users/profiles
Content-Type: application/json
Authorization: token {{authToken}}

{
    "image":"https://unsplash.com/photos/O3ymvT7Wf9U",
    "fullName":"Nhung Le"
}
### Get favorites 
GET http://localhost:5000/app/api/v1/users/favorite
Content-Type: application/json
Authorization: token {{authToken}}